name: SwiftLint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        run: swiftlint --config .swiftlint.yml --strict